# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Cressler Lab"  # Title of your website
description: "Cressler Lab | School of Biological Sciences | University of Nebraska-Lincoln"  # Description for your site
url: "https://claycressler.github.io"  # Replace with your GitHub Pages URL
baseurl: "/"  # Base URL for your website, leave as "/" if you're using the root

# Build settings
theme: jekyll-theme-cayman  # You can choose a theme or leave it blank
theme_settings:
  color: "blue"  # Example theme customization

# Permalink structure (if desired)
permalink: "/:categories/:year/:month/:day/:title"  # Customize if needed

# Navigation menu
menu:
  home: "/"
  people: "/people"
  research: "/research"
  publications: "/publications"

# Markdown settings (optional)
markdown: kramdown  # Default markdown processor
kramdown:
  input: GFM  # GitHub Flavored Markdown

# Plugins (optional)
plugins:
  - jekyll-seo-tag  # For SEO optimization
  - jekyll-feed  # RSS feed (optional)
